INSERT INTO items (name, done) 
VALUES ('Terminator', false),
('Terminator', true),
('Gojiro', true),
('A Place for us', false),
('A spark of light', false),
('You think it, I will say it', true),
('Tap & barrel', false),
('Boston pizza', true),
('Gusto di Quattro', false),
('Interstellar', true),
('Waiting', true),
('Skin care set', true),
('Red bikini', false),
('iPhone XS', false);